### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by debiasi** [samkuehn/bitbucket-backup#30]
I am running bitbucket backup and receiving this message:

Traceback (most recent call last):
  File "backup.py", line 161, in <module>
    if repo.get("slug") in args.ignore_repo_list:
TypeError: argument of type 'NoneType' is not iterable
Unknown error. (11)

Here is Python 2.6.9

**Comment by samkuehn** [comment]
This should be fixed now it was introduced in this commit https://github.com/samkuehn/bitbucket-backup/commit/fef51a204bfdd44333ef01b472f4289ae559fa6c.
Thanks @debiasi for bringing it to my attention.

**Comment by debiasi** [comment]
It worked ! Thanks for the fast answer !!!

**Comment by stantonk** [comment]
Ack! Sorry about that.
