### ISSUE TITLE
Use API key and avoid password

### ISSUE THREAD

**Issue by mnellemann** [samkuehn/bitbucket-backup#33]
Hi,

It there any chance that you could make the script use an API key to avoid having passwords in eg. cron-jobs?

**Comment by samkuehn** [comment]
I was unaware that Bitbucket supported API key authentication.  If you could point me in the direction of some documentation I would be happy to take a look.

**Comment by mnellemann** [comment]
Hi Sam,

There's some [api documentation](https://confluence.atlassian.com/display/BITBUCKET/Version+2) available, but I have not tested it. It looks like you can get a list of repositories belonging to a user or team. For teams you can create an API key within the "manage team", but for my normal account this was not possible.

**Comment by stantonk** [comment]
I think we should keep both forms.

**Comment by samkuehn** [comment]
@stantonk absolutely.  If added it will just be an additional authentication option.

**Comment by Yggdrasil** [comment]
:heart: I second this request. This will be especially useful when running bitbucket-backup via cronjobs.

**Comment by samkuehn** [comment]
I don't think you can get a token to access the Bitbucket api to get a listing of repositories.  It looks to me like they support http basic authentication (which we are using).  The only other authentication option that I see is OAuth which would require you log login to the website in order to get a bearer token which expires in 1 hour (at which point you need to use the refresh token to get a new bearer token).  While supporting this is possible it would be quite clunky as bitbucket-backup has no url to direct Bitbucket to in order to receive the token(s).  This would require copy and pasting tokens from URL's - I am just not sure it is worth the level of effort at this time.

Please let me know if I am missing something.

**Comment by jpSimkins** [comment]
How about UUID support?
https://confluence.atlassian.com/bitbucket/use-the-bitbucket-cloud-rest-apis-222724129.html#UsetheBitbucketCloudRESTAPIs-uuid-mainUniversallyUniqueIdentifier(UUID)

**Comment by samkuehn** [comment]
UUID support does not solve the authentication issue.  Calling:
curl https://api.bitbucket.org/2.0/repositories/samkuehn
curl https://api.bitbucket.org/2.0/repositories/%7Bde117435-a828-4f11-bfc8-89af539442af%7D/

Will give you the same result (no private repos).

**Comment by hongkongkiwi** [comment]
:-1:  to this request. I am backing up a team and this would be invaluable.

**Comment by ssasa** [comment]
To make it even more complicated, if you enable two-factor authorisation, then Basic HTTP auth stops to work and the backup script does not work any more. Found that info here https://blog.bitbucket.org/2015/09/10/two-step-verification-is-here/#comment-2250092492

**Comment by asadowski10** [comment]
👍 to this request too. I'm looking to find a new script to backing up a team and this would be invaluable.

**Comment by karlicoss** [comment]
@samkuehn (in reply to https://github.com/samkuehn/bitbucket-backup/issues/33#issuecomment-151642157 and https://github.com/samkuehn/bitbucket-backup/issues/33#issuecomment-161715633)

I'm pretty certain bitbucker API supports private repositories, I have a small python script which backs up all of my repos using oauth and it works fine, I don't have to get new token every hour or anything :) Although, your tool looks superior to mine, so I would be happy to contribute and implement OAuth authorization in it, and just dump mine.

In essence, you just add an OAuth consumer at Bitbucket settings -> Access management -> OAuth, then you just do usual oauth authorization sequence and get your access token. I've used [this](https://github.com/Sheeprider/BitBucket-api) library for api though, and I see this tool is using just plain HTTP requests, but that shouldn't be hard to implement.

**Comment by noderat** [comment]
@samkuehn Here's a shell script that uses the API key to do full backups that you can use as inspiration.

[bitbucket_backup.sh.txt](https://github.com/samkuehn/bitbucket-backup/files/402785/bitbucket_backup.sh.txt)

**Comment by samkuehn** [comment]
Thanks!  If I get some time this weekend I will work it.

**Comment by samkuehn** [comment]
I have added OAuth support.  It requires oauthlib  `pip install oauthlib`.  See README for instructions.

**Comment by karlicoss** [comment]
@samkuehn Sweet, it works! I just think readme is a bit misleading currently, instead

    Specify the -k <oauth_key> -s <oauth_secret> flags

it should be

   Specify the -k <consumer_key> -s <consumer_secret> flags

, since in context of oauth, 'oauth key/secret' are usually the keys issued by the consumer to users, someone who already had key/secret pair could spend several minutes figuring out why the script wouldn't accept them like me :D

**Comment by gldraphael** [comment]
Is it still possible to generate API keys for teams?

**Comment by samkuehn** [comment]
I think the only two ways to authenticate bitbucket api request are basic authentication (username/password) and oauth.

https://confluence.atlassian.com/bitbucket/use-the-bitbucket-cloud-rest-apis-222724129.html#UsetheBitbucketCloudRESTAPIs-Authentication

If there is a way to generate and api key to do authentication let me know.

**Comment by gldraphael** [comment]
Thanks!

Looks like there's no need for API keys. I can generate an app passwords and use that with basic authentication.

**Comment by sjlongland** [comment]
I'm running `bitbucket-backup` with `-s` and `-k` flags for OAuth2, but it appears it fails when it can't authenticate to the upstream repository.

Researching this, it appears another option is to use the access token obtained via OAuth2:
```
Cloning a repository with an access token

Since add-ons will not be able to upload their own SSH keys to clone with, access tokens can be used as Basic HTTP Auth credentials to clone securely over HTTPS.

$ git clone https://x-token-auth:{access_token}@bitbucket.org/user/repo.git

The literal string x-token-auth as a substitute for username is required.
```
https://confluence.atlassian.com/bitbucket/oauth-on-bitbucket-cloud-238027431.html

How hard would it be to implement this?
