### ISSUE TITLE
em dash causes issues when running in Jenkins

### ISSUE THREAD

**Issue by nlighteneddesign** [samkuehn/bitbucket-backup#39]
The script was working great locally, but when run through Jenkins it failed inexplicably,

**Comment by ronlipke** [comment]
This fails because, by default, the Jenkins output cannot handle non-ascii characters and the `debug` function is not strict encoding the output of printf.  An easy fix is to add `export PYTHONIOENCODING=UTF-8` to any python Jenkins jobs.
