### ISSUE TITLE
Invoking backup does not update the repo

### ISSUE THREAD

**Issue by ssasa** [samkuehn/bitbucket-backup#42]
Hi,
The script is invoked in this way:

bitbucket-backup -u <some-username> -l /mnt/backup/bitbucket -p <some-password> -t <some-team> --with-wiki

It works. At least there are no visible errors.

According to README file bitbucket-backup works as "git update" when invoked next time. But this is not the case here as files are not updated after invoking the program again. But when going to a certain repo and invoking manually "git update" then the repo is updated (which means SSH keys are working properly).

Am I using this in a wrong way, or there is a bug?
What additional info can I provide to help debug this?
Thanks!
Sasa

**Comment by samkuehn** [comment]
I have fixed the verbosity flag to work properly.  Can you try pulling the new version and running bitbucket-backup with -v?

**Comment by ssasa** [comment]
After update and running with -v this is the output of a project that had changes:

2016-01-29 17:40:01.552323 - Executing command: git remote update
Fetching origin
2016-01-29 17:40:06.848815 - Backing up [core]...
2016-01-29 17:40:06.848970 - Repository [core] already in place, just updating...
2016-01-29 17:40:06.849007 - Updating core...
2016-01-29 17:40:06.849025 - Executing command: git remote update
Fetching origin
remote: Counting objects: 56, done.
remote: Compressing objects: 100% (56/56), done.
remote: Total 56 (delta 19), reused 0 (delta 0)
Unpacking objects: 100% (56/56), done.
From bitbucket.org:microblink/core
   c880a73..bbf3eed  master     -> origin/master
2016-01-29 17:40:39.873517 - Updating core's Wiki...

It looks like merge or pull is missing. When "git status" is invoked in the mentioned project this is the output:

On branch master
Your branch is behind 'origin/master' by 13 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
nothing to commit, working directory clean

**Comment by samkuehn** [comment]
The `git remote update` should fetch all of the data from the remote but not move the HEAD.  You should be able to "fast forward" by running `git rebase`.   It is sort of like the difference between a git fetch and a git pull.   I could run `git pull -all` after the `git remote update` but I am not sure if this is a good idea or not.  Open to suggestions.

**Comment by ssasa** [comment]
I have discussed with the team, and we are looking at bitbucket-backup as a backup tool, which has a purpose to "remember" the state which was present at the moment when bitbucket-backup runs. If it runs on daily basis (as in our case), then we would favour that `git pull -all` is used, as this would give the exact state valid on the moment when bitbucket-backup runs.

**Comment by samkuehn** [comment]
Sorry I have not got back to you.  I was on vacation.  Would this https://github.com/samkuehn/bitbucket-backup/commit/2aac4e548b4b5dda19b6ef4f54adaa231784ccba solution work for you (it is in the pull branch)?

**Comment by ssasa** [comment]
This is looking good. It will backup current branches (but not the new ones).

In the long run, it would be even better if bitbucket-backup could backup all branches, including the new one that arrives.

**Comment by jonadem** [comment]
I tried the "pull" branch version but I ran into the problem of empty repositories (it makes the script stops).
If this is also a case you want to consider, a workaround can be to test if HEAD exists with `git ls-remote "$REPO_URL" HEAD`
I don't have a working patch yet.
Hope this helps !

**Comment by ahidalgo82** [comment]
is this something that is still being worked on? I do like the idea of a `git pull --all`. I do also like the idea of git checkout all branches to have "all" the problem then becomes pruning. I would prefer if the backup is exactly as the remote.

Thanks for this tool! Great work.
