### ISSUE TITLE
Continue on to next repo if error occurs

### ISSUE THREAD

**Issue by scottlinux** [samkuehn/bitbucket-backup#51]
Thank you for this awesome tool. Is it possible should an error occur on one particular repo, for the script to go on and continue backups for the following repos?

Thank you,

**Comment by samkuehn** [comment]
I am a little hesitant to do that as it is possible that people are relying on the program exiting with an unsuccessful error code as part of a larger bash script or something.  That said I probably could add a flag that tells the program to continue upon exception.  Any idea what exceptions I should try and catch?  Don't love the idea of catch the broad general exception but that might be the only way to go.

**Comment by samkuehn** [comment]
Have you tried the -a --attempts flag (max. number of attempts to backup repository)?

**Comment by scottlinux** [comment]
I see, yeah a flag would be a nice touch for a feature.

As far as exceptions, I am not sure. I think perhaps ssh-related such as permission denied (wrong or no ssh key) or a timeout of some kind if bitbucket was having trouble are useful.

I have used the --attempts flag, on a repo that had trouble (permission denied) it attempted that number of times (tried 2) then the entire script aborted. So same behavior as without --attempts.

Thanks,

**Comment by samkuehn** [comment]
Will probably just catch any exception and log.
