### ISSUE TITLE
Missing backup of LFS files

### ISSUE THREAD

**Issue by mariocrist** [samkuehn/bitbucket-backup#54]
I don't  see any option to bring files in LFS

**Comment by samkuehn** [comment]
I have never actually had a reason to use LFS so it is completely foreign to me.  However, it looks like a standard `git clone`/ `git pull` _should_ grab those assets, but I am not sure.

**Comment by mariocrist** [comment]
I'm trying to backup with option `--mirror`. And this is not implemented in `clone / pull` [https://github.com/git-lfs/git-lfs/issues/2342](url)
I have added `git lfs fetch origin --all` after `clone / pull`

**Comment by frenkel** [comment]
@samkuehn it works for non-bare repo's I think, it will hook into the smudge filter. bitbucket-backup probably does bare or mirror clones.

**Comment by frenkel** [comment]
@samkuehn Why did you close this? Not going to implement it, or was it added already?
