### ISSUE TITLE
Bitbucket returned HTTP error [403]. (1)

### ISSUE THREAD

**Issue by LucianYoga** [samkuehn/bitbucket-backup#55]
Hello, 
 This used to work great but now after turning 2 factor authentication getting an error
Connection Error! Bitbucket returned HTTP error [403]. (1)
Any ideas?

Thanks

**Comment by kellykmercury** [comment]
Late reply but if you are using 2FA, you will not be able to make HTTP/HTTPS connections to your account.  It specifically states this when you turn on 2FA in your BitBucket account.

**Comment by jonadem** [comment]
For me, the script has also worked for 400 days but since yesterday I get :
Connection Error! Bitbucket returned HTTP error [410]

I don't think that something has changed in our IT. Does someone have an idea ?
