### ISSUE TITLE
Bitbucket 2.0 API update

### ISSUE THREAD

**Issue by Boojs** [samkuehn/bitbucket-backup#61]
Hi,

Just wondering if there is any movement or thought on migrating to the 2.0 api as the 1.0 api is now deprecated as of April 29th 2019. I'm trying to work through the oauth flow myself and can get it to work on some test scripts. But getting that migrated into this has been a bit of a challenge for myself.

Hope to hear from someone soon!

Thanks a lot

**Comment by samkuehn** [comment]
I did this over the weekend as the V1 API started returning 410s.  It appears to me (could be wrong) that the v2 API no longer supports OAuth1, so it was removed. https://developer.atlassian.com/bitbucket/api/2/reference/meta/authentication

For now, perhaps, the answer is application passwords for authentication https://confluence.atlassian.com/bitbucket/app-passwords-828781300.html.  We might be able to get OAuth2 working but that would require logging into BitBucket and persisting tokens somewhere.

**Comment by Boojs** [comment]
@samkuehn 

Thanks for the quick response. OAuth still works, just need to get the authorization token now to query the 2.0 api. This is my dumb little script to get it working.

`
import requests
import json
import sys

data = {
  'grant_type': 'client_credentials'
}

client = oauthlib.oauth1.Client(self.oauth_key, client_secret=self.oauth_secret)
response = requests.post('https://bitbucket.org/site/oauth2/access_token', data=data, auth=client)

respData = json.loads(response.content)
token=(respData['access_token'])

headers = {
    'Authorization': 'Bearer ' + token,
}

repos = requests.get('https://api.bitbucket.org/2.0/users/<team_account>/repositories', headers=headers)
print repos.content
`

The problem I'm having after this though is the parsing of the actual repos in the lambda function

**Comment by Boojs** [comment]
@samkuehn I have it working finally. I will try to get a PR up for you and see if you'd like to merge it or not.

**Comment by rangermann** [comment]
Hi, 

Any news on this?

**Comment by samkuehn** [comment]
I can look at adding this but I am curious why don't you use app passwords? https://confluence.atlassian.com/bitbucket/app-passwords-828781300.html

Seems more flexible and straight forward.

**Comment by fpracht** [comment]
Until recently, we did the backup with OAuth authentication. OAuth was not configured for one user, but in the team settings. We would like to keep it that way, but there are no app passwords in the team settings. Only OAuth is available. In this case it makes sense to have OAuth.

**Comment by Boojs** [comment]
@samkuehn So I noticed I still am using an old version of your script from a few commits back, but I got it to work with regular oauth with access tokens. Also like you said, can just use app passwords.

I would happy to create a PR but am unable to, the button is greyed out for me. Not sure whats up there?

The chunk of code you need is this

`        if all((self.oauth_key, self.oauth_secret)):
            try:
                import oauthlib.oauth1
            except ImportError:
                import sys
                print("You must install oauthlib if you want to use oauth `pip install oauthlib`")
                sys.exit(0)
            grant_data = {'grant_type': 'client_credentials'}
            auth_req = requests.post(token_url, data=grant_data, auth=(self.oauth_key, self.oauth_secret))
            respData = json.loads(auth_req.content)
            token=(respData['access_token'])
            headers = {
                'Authorization': 'Bearer ' + token,
            }
            request = Request(url, data, headers)
            return request`

**Comment by samkuehn** [comment]
I have added OAuth authentication back into the script.
https://github.com/samkuehn/bitbucket-backup/commit/58c702b8776ec190dd9c7cac7cf977e02c8a81a6


Let me know if this works for you now.

**Comment by rangermann** [comment]
@Boojs @samkuehn Thanks - I already switched to app passwords now, and got it working again (my issue was intially the broken teams API).

**Comment by Boojs** [comment]
@samkuehn I dont believe this will work. Their new OAuth flow requires you to grab an access token first, then authenticate with that as per my code snippet above

**Comment by samkuehn** [comment]
It worked for me in testing.  I think the requests library handles the OAuth handshake.

**Comment by fpracht** [comment]
I can confirm that OAuth ist working again. Thank you.
