### ISSUE TITLE
Couldn't backup new repos with API2 due to wrong username

### ISSUE THREAD

**Issue by thekvs** [samkuehn/bitbucket-backup#62]
I've generated new app password on bitbucket as suggested [here](https://confluence.atlassian.com/bitbucket/app-passwords-828781300.html) specifically for this utility and all seems to work when I backup (update via `git fetch`) already backed up repositories. But when I try to backup repository that doesn't yet exist locally this utility fails because it uses invalid bitbucket username to clone repo, i.e. not the one I have on bitbucket.

Failed command looks like: `git clone --mirror git@bitbucket.org:*INVALID_USERNAME*/repo.git "/path/to/backup/location"`

I have a hunch that it takes username either from `.gitconfig` or uses my local login and not username that I use on bitbucket.

**Comment by samkuehn** [comment]
The `git clone` command should be using the username that you pass in: `-u <username>`

https://github.com/samkuehn/bitbucket-backup/blob/master/backup.py#L172

**Comment by thekvs** [comment]
That's very strange. Even if I enter bitbucket's username interactively (by not specifying `--username` option) script still uses a wrong one.

**Comment by thekvs** [comment]
I'd like to add that script knows private repositories' names so it means that it logs in into bitbucket successfully and reads list of repositories to backup.

**Comment by thekvs** [comment]
Shouldn't there https://github.com/samkuehn/bitbucket-backup/blob/master/backup.py#L182 be `quote(username)` ?

**Comment by nintenic** [comment]
I also have this issue, and I think I've found the cause of the problem.

The username that is pulled is from the Atlassian "public name", which doesn't have to be the same as your bitbucket username.
